podman run -d \
  --name traefik \
  --restart=unless-stopped \
  --network proxy \
  --dns=1.1.1.1 --dns=8.8.8.8 \
  -p 80:80 \
  -p 443:443 \
  --env-file "$HOME/traefik/cf.env" \
  -v /run/user/$(id -u)/podman/podman.sock:/var/run/docker.sock:ro \
  -v "$HOME/traefik/data:/data" \
  -v "$HOME/traefik/secrets:/secrets:ro" \
  -l "traefik.enable=true" \
  -l "traefik.http.routers.traefik.rule=Host(\`traefik.az-lab.dev\`)" \
  -l "traefik.http.routers.traefik.entrypoints=websecure" \
  -l "traefik.http.routers.traefik.tls=true" \
  -l "traefik.http.routers.traefik.tls.certresolver=le" \
  -l "traefik.http.routers.traefik.service=api@internal" \
  -l "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/secrets/traefik.htpasswd" \
  -l "traefik.http.middlewares.traefik-allow.ipallowlist.sourcerange=192.168.1.0/24,10.7.0.0/24,10.89.0.0/16" \
  -l "traefik.http.routers.traefik.middlewares=traefik-allow,traefik-auth" \
  docker.io/traefik:v3.1 \
  --log.level=INFO \
  --accesslog=true \
  --api.dashboard=true \
  --entrypoints.web.address=:80 \
  --entrypoints.websecure.address=:443 \
  --entrypoints.web.http.redirections.entrypoint.to=websecure \
  --entrypoints.web.http.redirections.entrypoint.scheme=https \
  --providers.docker=true \
  --providers.docker.endpoint=unix:///var/run/docker.sock \
  --providers.docker.exposedbydefault=false \
  --certificatesresolvers.le.acme.email=YOUREMAIL@example.com \
  --certificatesresolvers.le.acme.storage=/data/acme.json \
  --certificatesresolvers.le.acme.dnschallenge=true \
  --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare \
  --certificatesresolvers.le.acme.dnschallenge.delaybeforecheck=10 \
  --certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
